#! /bin/sh

# Single monitor
bspc monitor -d I II III IV V

# Dual Monitor (find names with xrandr --query)
# bspc monitor DP-2 -d I II III IV V 
# bspc monitor HDMI-0 -d VI VII VII IX X


bspc config border_width 2
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 3
bspc config left_padding 3
bspc config single_monocle false

## BSPWM coloring
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 1600×900+0+0 center=true
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a st state=floating layer=normal
bspc rule -a mpv state=floating layer=normal rectangle 1920x1080+0+0
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal rectangle 1200x900+0+0
bspc rule -a 'GitHub Desktop' desktop='^2' follow=on
bspc rule -a Gimp desktop='^9' follow=on
bspc rule -a obs desktop='^10' follow=on
bspc rule -a discord desktop='^8' follow=on

## Polybar or tint
~/.config/bspwm/polybar/lauch.sh &

## apps for systray if enabled
# volumeicon &
# nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi

# Autostart

## Dual monitor
# xrandr --output HDMI-0 --mode 1920x1080 --output DP-2 --mode 2560x1440 --scale 0.8 --rate 180 --primary --right-of HDMI-0

# Polkit

# Iniciar o agente de autenticação do Gnome (polkit)
if ! pgrep -x /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 > /dev/null; then
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi
## Layout do teclado
setxkbmap -layout us -variant intl &

## Compositor do ambiente
picom --animations -b --config ~/.config/bspwm/picom/picom.conf &

## Pano de fundo da área de trabalho sempre mudando
## Preserva com nitrogem e muda com o feh
# nitrogen --restore &
feh --randomize --no-fehbg --bg-fill ~/.config/bspwm/wallpapers/ &

## Define explicitamente o tema e o tamanho do cursor
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24
xsetroot -cursor_name left_ptr

## Som
pipewire&

## Bluetooth ativado
bluetoothctl power on &

## Notificações
dunst -config ~/.config/bspwm/dunst/dunstrc &

## Polybar
bash ~/.config/bspwm/polybar/launch.sh >> ~/.polybar.log 2>&1 &

## Rede
# nm-applet &

## Captura de tela
flameshot &

## Controlar bluetooth
blueman-applet &

## Evitar que a tela desligue
xset s off -dpms s noblank &
