#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config presel_feedback_color "#2f363d"
bspc config active_border_color		"#539bf5"
bspc config focused_border_color "#539bf5"
bspc config normal_border_color "#2f363d"

# bspc rule -a "*" split_dir=east
bspc rule -a \* rectangle 1600×900+0+0 center=true
bspc rule -a qimgv state=floating
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a st state=floating layer=normal
bspc rule -a scratchpad state=floating layer=normal
bspc rule -a pulsemixer state=floating layer=normal
bspc rule -a Galculator state=floating layer=normal rectangle=900x600+0+0
bspc rule -a mpv state=floating layer=normal rectangle 1920x1080+0+0
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal rectangle 1200x900+0+0
bspc rule -a 'GitHub Desktop' desktop='^2' follow=on
bspc rule -a Gimp desktop='^9' follow=on
bspc rule -a obs desktop='^10' follow=on
bspc rule -a discord desktop='^8' follow=on

xsetroot -cursor_name left_ptr &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst -config ~/.config/bspwm/dunst/dunstrc &
picom --config ~/.config/bspwm/picom/picom.conf --animations -b &
feh --bg-fill ~/.config/bspwm/wallpaper/wallhaven-vq76dp_3440x1440.png &

## Polybar or tint
~/.config/bspwm/polybar/polybar-bspwm &

## apps for systray if enabled
# volumeicon &
# nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sleep 0.5
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
